### ISSUE TITLE
are you sure the url used in project is government website?

### ISSUE THREAD

**Issue by vivek80801** [Arsenic-ATG/Scheme-Scraper#2]
are you sure the url used in project is government website?

the most accurate information will be on government website.

In [This File](https://github.com/Arsenic-ATG/Scheme-Scraper/blob/main/scraper.py "go to file")

```python
url = "https://krishijagran.com/agripedia/best-government-schemes-and-programmes-in-agriculture-for-farmers/"
```

**Comment by Arsenic-ATG** [comment]
nope, it's a news site instead. the government site have much more complicates structure and lesser freedom for scraper to move around.

as this is in it's initial state and the hackathon was time constrained so went for a much simpler structure site instead.

**Comment by vivek80801** [comment]
@Arsenic-ATG  Please read again my question and why I am asking?

**Comment by Arsenic-ATG** [comment]
@vivek80801 now I get it.

Actually, the original idea of the scraper was to get information of the latest scheme in real time. It was the time constrain of competition which stoped to do so and we(our team) have to resort to a news site with a comparatively simpler site.

But now as the competition is over, I will soon be upgrading this scraper to work in it's full potential and in real time.

Also can you send me the link to the site from where you get the information and fill the forms, so that I can prefer it over other sites as target.

----

As far a legal issues are concerned, as far as i know that vary from site to site and the stuff the scraper is doing on the site. 

For example if a scraper make too many requests for the page and increase the server load of the site then it can be a problem.
